[workspace]

members = [
    "kelp_engine",
    "kelp_perft"
]

default-members = [
    "kelp_engine",
    "kelp_perft"
]

[profile.release]
opt-level = 3
debug-assertions = false
codegen-units = 1
lto = true
panic = "abort"
